const types = {
    SET_USER_TOKEN: "SET_USER_TOKEN",
    SET_ALL_TASK: 'SET_ALL_TASKS',
    ACTIVATE_SNACK_BAR: 'ACTIVATE_SNACK_BAR',
    DEACTIVATE_SNACK_BAR:'DEACTIVATE_SNACK_BAR'
}

export default types;
